fix: Add missing semicolons
This fix a compilation error caused by missing semicolons

msi-ec.c:60:2: error: expected ';' after top level declarator
   60 | }
      |  ^
      |  ;

msi-ec.c:2831:53: error: expected ';' after expression
 2831 |                 pr_err("Your firmware version is blacklisted !\n")
      |                                                                   ^
      |

Signed-off-by: Eric Lin <ericlin050914@gmail.com>